PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ordo: <http://www.orpha.net/ORDO/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT distinct ?condition_occurrence_id ?person_id ?condition_concept_id ?condition_start_date ?condition_start_datetime ?condition_end_date ?condition_end_datetime ?condition_type_concept_id ?condition_status_concept_id ?stop_reason ?provider_id
 ?visit_occurrence_id ?visit_detail_id ?condition_source_value ?condition_source_concept_id ?condition_status_source_value ?visit_concept_id ?visit_start_date ?visit_start_datetime ?visit_end_time ?visit_end_datetime ?visit_type_concept_id ?provider_id ?care_site_id ?visit_source_value ?visit_source_concept_id ?admitting_source_concept_id ?admitting_source_value ?discharge_to_concept_id ?discharge_to_source_value ?preceding_visit_occurrence_id

WHERE {

    GRAPH ?g {

        ?id sio:SIO_000020 ?role ; sio:SIO_000300 ?person_id .
        ?role sio:SIO_000356 ?process ; a sio:SIO_000016 .
        ?process a sio:SIO_000006, ?process_type ; sio:SIO_000229 ?output .
        ?output sio:SIO_000628 ?attribute; a sio:SIO_000015 . 
        ?attribute a sio:SIO_000614, obo:NCIT_C124353 .

        ?output sio:SIO_000300 ?condition_start_date, ?condition_end_date .
        FILTER (datatype(?condition_start_date) = xsd:date ).

        
        ?process sio:SIO_000291 ?target.
        ?target a sio:SIO_000015, ?condition_source_value .
        FILTER (?condition_source_value != sio:SIO_000015)
    }
    ?g a sio:SIO_001027 ; sio:SIO_000068 ?event ;
                           sio:SIO_000680 ?startdate;
                           sio:SIO_000681 ?enddate;
                           sio:SIO_000300 ?condition_occurrence_id .
        
    ?startdate a sio:SIO_000031 .
    ?enddate a sio:SIO_000032 .
        
    ?event a sio:SIO_000088 ; sio:SIO_000300 ?visit_occurrence_id .
        
    ?startdate sio:SIO_000300 ?visit_start_date .
    ?enddate sio:SIO_000300 ?visit_end_time .
}