PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ordo: <http://www.orpha.net/ORDO/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT DISTINCT

  ?observation_id
  ?person_id
  ?observation_concept_id
  ?observation_date
  ?observation_datetime
  ?observation_type_concept_id
  ?value_as_number
  ?value_as_string
  ?value_as_concept_id
  ?qualifier_concept_id
  ?unit_concept_id
  ?provider_id
  ?visit_occurrence_id
  ?visit_detail_id
  ?observation_source_value
  ?observation_source_concept_id
  ?unit_source_value
  ?qualifier_source_value
  ?value_source_value
  ?observation_event_id
  ?obs_event_field_concept_id

  ?visit_concept_id
  ?visit_start_date
  ?visit_start_datetime
  ?visit_end_date
  ?visit_end_datetime
  ?visit_type_concept_id
  ?care_site_id
  ?visit_source_value
  ?visit_source_concept_id
  ?admitted_from_concept_id
  ?admitted_from_source_value
  ?discharged_to_concept_id
  ?discharged_to_source_value
  ?preceding_visit_occurrence_id

WHERE {
    GRAPH ?g { # Participation Status

        ?id sio:SIO_000020 ?role ; sio:SIO_000300 ?person_id .
        ?role sio:SIO_000356 ?process ; a sio:SIO_000016 .
        ?process a sio:SIO_000006; sio:SIO_000229 ?output .
        ?output sio:SIO_000628 ?attribute; a sio:SIO_000015, obo:NCIT_C164628 . 
        ?attribute a sio:SIO_000614,?observation_source_value . 
        FILTER (?observation_source_value != sio:SIO_000614) 
    }

    ?g a sio:SIO_001027 ; sio:SIO_000068 ?event ;
                           sio:SIO_000680 ?startdate;
                           sio:SIO_000681 ?enddate;
                           sio:SIO_000300 ?observation_id .
        
    ?startdate a sio:SIO_000031 .
    ?enddate a sio:SIO_000032 .
        
    ?event a sio:SIO_000088 ; sio:SIO_000300 ?visit_occurrence_id .
        
    ?startdate sio:SIO_000300 ?condition_start_date, ?visit_start_date, ?observation_date .
    ?enddate sio:SIO_000300 ?condition_end_date , ?visit_end_date .

    }